<?php

/**
 * CSV "Продукт (RU)" → ingilis adı (EN). GunAzParsingStrategySeeder / LocalizedJson üçün.
 * Açarlar fayldakı RU mətni ilə tam üst-üstə düşməlidir (trim).
 */
return [

    'by_ru' => [
        'Coca-Cola' => 'Coca-Cola',
        'Qatıq' => 'Yogurt',
        'Авокадо' => 'Avocado',
        'Айран' => 'Ayran',
        'Апельсины' => 'Oranges',
        'Арбуз' => 'Watermelon',
        'Багет' => 'Baguette',
        'Баклажан' => 'Eggplant',
        'Бананы' => 'Bananas',
        'Баранина' => 'Lamb (meat)',
        'Баранья корейка' => 'Lamb ribs',
        'Батон белый' => 'White loaf bread',
        'Булгур' => 'Bulgur',
        'Варенье' => 'Jam',
        'Вермишель' => 'Vermicelli',
        'Виноград' => 'Grapes',
        'Вода' => 'Water',
        'Говядина' => 'Beef',
        'Говяжий фарш' => 'Ground beef',
        'Горошек конс.' => 'Canned green peas',
        'Горчица' => 'Mustard',
        'Гранат' => 'Pomegranate',
        'Грецкий орех' => 'Walnuts',
        'Гречка' => 'Buckwheat',
        'Груша' => 'Pear',
        'Детская смесь' => 'Baby formula',
        'Детское пюре' => 'Baby puree',
        'Дыня' => 'Melon',
        'Дюшбара' => 'Dushbara (dumplings)',
        'Зубная паста' => 'Toothpaste',
        'Изюм' => 'Raisins',
        'Имбирь' => 'Ginger',
        'Индейка' => 'Turkey',
        'Йогурт питьевой' => 'Drinking yogurt',
        'Кабачок' => 'Zucchini',
        'Капуста' => 'Cabbage',
        'Картофель' => 'Potatoes',
        'Кетчуп' => 'Ketchup',
        'Кефир' => 'Kefir',
        'Киви' => 'Kiwi',
        'Кинза' => 'Cilantro',
        'Клубника' => 'Strawberries',
        'Колбаса варёная' => 'Boiled sausage',
        'Колбаса копч.' => 'Smoked sausage',
        'Компот' => 'Compote',
        'Кофе' => 'Coffee',
        'Креветки' => 'Shrimp',
        'Кукуруза' => 'Corn',
        'Кукуруза конс.' => 'Canned corn',
        'Кукурузная' => 'Corn (groats)',
        'Кукурузное' => 'Corn oil',
        'Курага' => 'Dried apricots',
        'Курдюк' => 'Tail fat (fat-tailed sheep)',
        'Куриное филе' => 'Chicken fillet',
        'Куриные бёдра' => 'Chicken thighs',
        'Куриные крылья' => 'Chicken wings',
        'Курица целая' => 'Whole chicken',
        'Куркума' => 'Turmeric',
        'Кутум' => 'Kutum (fish)',
        'Лаваш' => 'Lavash',
        'Лавашана' => 'Lavashana',
        'Лимон' => 'Lemon',
        'Лук' => 'Onion',
        'Майонез' => 'Mayonnaise',
        'Макароны' => 'Penne pasta',
        'Мандарины' => 'Mandarins',
        'Манка' => 'Semolina',
        'Маргарин' => 'Margarine',
        'Маслины' => 'Black olives',
        'Масло слив.' => 'Butter',
        'Миндаль' => 'Almonds',
        'Минералка' => 'Mineral water',
        'Молоко' => 'Milk',
        'Морковь' => 'Carrots',
        'Мороженое' => 'Ice cream',
        'Мука' => 'Flour',
        'Мята' => 'Mint',
        'Мёд' => 'Honey',
        'Наршараб' => 'Pomegranate molasses (narsharab)',
        'Нут' => 'Chickpeas',
        'Овощная смесь' => 'Frozen vegetable mix',
        'Овсянка' => 'Oat flakes (Hercules)',
        'Огурцы' => 'Cucumbers',
        'Оливковое' => 'Olive oil',
        'Осётр' => 'Sturgeon',
        'Перепелиные' => 'Quail eggs',
        'Перец болг.' => 'Bell pepper',
        'Перец острый' => 'Hot pepper',
        'Перец чёрный' => 'Black pepper',
        'Перловка' => 'Pearl barley',
        'Персик' => 'Peach',
        'Петрушка' => 'Parsley',
        'Печень' => 'Liver',
        'Печенье' => 'Cookies',
        'Пиво местное' => 'Beer (local)',
        'Плавленый сыр' => 'Processed cheese',
        'Подгузники' => 'Diapers',
        'Подсолнечное' => 'Sunflower oil',
        'Помидоры' => 'Tomatoes',
        'Пшено' => 'Millet',
        'Редис' => 'Radish',
        'Рейхан' => 'Basil (reyhan)',
        'Ржаной' => 'Rye bread',
        'Рис' => 'Rice',
        'Рис басмати' => 'Basmati rice',
        'Салат' => 'Lettuce',
        'Сахар' => 'Sugar',
        'Свёкла' => 'Beetroot',
        'Сгущёнка' => 'Sweetened condensed milk',
        'Семечки' => 'Sunflower seeds',
        'Слива' => 'Plum',
        'Сливки' => 'Cream',
        'Сметана' => 'Sour cream',
        'Сок' => 'Juice',
        'Соль' => 'Salt',
        'Сосиски' => 'Sausages',
        'Спагетти' => 'Spaghetti',
        'Ср-во д/посуды' => 'Dishwashing liquid',
        'Стир. порошок' => 'Laundry detergent',
        'Суджук' => 'Sujuk (sausage)',
        'Сулугуни' => 'Sulguni cheese',
        'Сумах' => 'Sumac',
        'Сыр белый' => 'White brined cheese',
        'Сыр твёрдый' => 'Hard cheese',
        'Сёмга' => 'Salmon',
        'Творог' => 'Cottage cheese',
        'Телятина' => 'Veal',
        'Тендир' => 'Tandir bread',
        'Тесто слоёное' => 'Puff pastry',
        'Томатная паста' => 'Tomato paste',
        'Топлёное' => 'Ghee (clarified butter)',
        'Туал. бумага' => 'Toilet paper',
        'Тунец конс.' => 'Canned tuna',
        'Тыква' => 'Pumpkin',
        'Укроп' => 'Dill',
        'Уксус' => 'Vinegar',
        'Фарш бараний' => 'Ground lamb',
        'Фасоль' => 'Beans',
        'Финики' => 'Dates',
        'Фисташки' => 'Pistachios',
        'Форель' => 'Trout',
        'Фундук' => 'Hazelnuts',
        'Халва' => 'Halva',
        'Хлебцы' => 'Crispbread',
        'Хурма' => 'Persimmon',
        'Чай зелёный' => 'Green tea',
        'Чай чёрный' => 'Black tea',
        'Чернослив' => 'Prunes',
        'Чеснок' => 'Garlic',
        'Чечевица' => 'Lentils',
        'Шампиньоны' => 'Mushrooms (button)',
        'Шампунь' => 'Shampoo',
        'Шафран' => 'Saffron',
        'Шоколад' => 'Chocolate',
        'Энергетик' => 'Energy drink',
        'Юха' => 'Yuxa (flatbread)',
        'Яблоки' => 'Apples',
        'Яйца куриные' => 'Chicken eggs',
    ],

    /**
     * AZ adı ilə ehtiyat açarı (RU xəritədə yoxdursa).
     */
    'by_az' => [
        'Süd' => 'Milk',
        'Qatıq' => 'Yogurt',
    ],

    /**
     * CSV kateqoriya sütunu (emoji çıxarılmış RU başlıq) → üç dil.
     *
     * @var array<string, array{az: string, en: string, ru: string}>
     */
    'category' => [
        'Молочные' => ['az' => 'Süd məhsulları', 'en' => 'Dairy', 'ru' => 'Молочные'],
        'Хлеб' => ['az' => 'Çörək', 'en' => 'Bread', 'ru' => 'Хлеб'],
        'Крупы' => ['az' => 'Taxıl', 'en' => 'Grains & cereals', 'ru' => 'Крупы'],
        'Макароны' => ['az' => 'Makaron', 'en' => 'Pasta', 'ru' => 'Макароны'],
        'Мясо' => ['az' => 'Ət', 'en' => 'Meat', 'ru' => 'Мясо'],
        'Рыба' => ['az' => 'Balıq', 'en' => 'Fish & seafood', 'ru' => 'Рыба'],
        'Яйца' => ['az' => 'Yumurta', 'en' => 'Eggs', 'ru' => 'Яйца'],
        'Масла' => ['az' => 'Yağlar', 'en' => 'Oils & fats', 'ru' => 'Масла'],
        'Овощи' => ['az' => 'Tərəvəz', 'en' => 'Vegetables', 'ru' => 'Овощи'],
        'Зелень' => ['az' => 'Göyərti', 'en' => 'Herbs & greens', 'ru' => 'Зелень'],
        'Фрукты' => ['az' => 'Meyvə', 'en' => 'Fruits', 'ru' => 'Фрукты'],
        'Орехи' => ['az' => 'Qoz-fındıq', 'en' => 'Nuts', 'ru' => 'Орехи'],
        'Бакалея' => ['az' => 'Ərzaq', 'en' => 'Groceries', 'ru' => 'Бакалея'],
        'Консервы' => ['az' => 'Konserv', 'en' => 'Canned goods', 'ru' => 'Консервы'],
        'Заморозка' => ['az' => 'Dondurulmuş', 'en' => 'Frozen', 'ru' => 'Заморозка'],
        'Колбасы' => ['az' => 'Kolbasa', 'en' => 'Sausages & deli', 'ru' => 'Колбасы'],
        'Сладости' => ['az' => 'Şirniyyat', 'en' => 'Sweets', 'ru' => 'Сладости'],
        'Напитки' => ['az' => 'İçkilər', 'en' => 'Beverages', 'ru' => 'Напитки'],
        'Детское' => ['az' => 'Uşaq məhsulları', 'en' => 'Baby products', 'ru' => 'Детское'],
        'Хозтовары' => ['az' => 'Məişət', 'en' => 'Household goods', 'ru' => 'Хозтовары'],
    ],

];
